title: Default
items:
  home:
    title: 'Home'
    url: 'home'
    order: 1
  blog:
    title: 'Blog'
    url: 'blog'
    order: 2
  about:
    title: 'About'
    url: 'about'
    order: 3
