# The title of the website
title: "Flextype"

# The description of the website
description: "Modern Open Source Flat-File Content Management System"

# The keywords of the website
keywords: "flextype, php, cms, flat-file cms, flat cms, flatfile cms, html"

# The robots of the website
robots: "index, follow"

# The name and email address of the website author
author:
  email: ""
  name: ""

# Set the timezone to be used on the website.
# For a list of valid timezone settings, see:
# http://php.net/manual/en/timezones.php
timezone: UTC

# Charset
#
# Set internal character encoding.
#
# Currently the following names are supported:
# http://php.net/manual/ru/function.mb-regex-encoding.php#121645
charset: UTF-8

# Valid date format
# see: http://php.net/manual/ru/function.date.php
date_format: "F d Y H:i:s"

# The theme to use.
#
# Don't edit the provided theme templates directly, because they get updated
# in next releases. If you wish to modify a default theme, copy its folder, and
# change the name here accordingly.
theme: default

# The locale that'll be used by the Flextype.
locale: "en"

# The entries settings
# Define the file types (extensions to be exact) that are acceptable for upload.
entries:
  main: home
  media:
    upload_images_quality: 70
    upload_images_width: 1600
    upload_images_height: 0
    accept_file_types: "gif, jpg, jpeg, png, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg"
  error404:
    title: "Error 404"
    description: "We're sorry but the page you are looking for doesn't appear to exist!"
    content: "We're sorry but the page you are looking for doesn't appear to exist!"
    template: "default"

# Display errors
errors:
  display: false

# Cache
# available drivers: auto (will get one from installed cache drivers), apcu,
# apc, wincache, xcache, memcache, memcached, redis, file.
cache:
  enabled: true
  prefix: flextype
  driver: auto
  lifetime: 604800
