title: Flextype
description: 'Modern Open Source Flat-File Content Management System'
keywords: 'flextype, php, cms, flat-file cms, flat cms, flatfile cms, markdown'
robots: 'index, follow'
author:
  name: 'Sergey Romanenko'
  email: ''
timezone: UTC
date_format: 'F d Y H:i:s.'
charset: UTF-8
theme: default
locale: en
pages:
  main: home
errors:
  display: true
cache:
  enabled: true
  prefix: Flextype
  driver: auto
  lifetime: 604800
