title: "Flextype"
description: "The Best Open Source Flat-File Content Management System"
keywords: "flextype, php, cms, flat-file cms, flat cms, flatfile cms, markdown"
robots: "index, follow"
author:
  name: "Sergey Romanenko"
  email: ""

social_link:
  twitter: "https://twitter.com/getflextype"
  github: "https://github.com/flextype"
  gitter: "https://gitter.im/flextype/flextype"
  vkontakte: "https://vk.com/flextype"
  telegram: "http://t.me/flextype"
