#
# Site configuration
#

title: "Flextype"
description: "The Best Open Source Flat-File Content Management System"
author:
  email: ""

timezone: UTC
charset: UTF-8
date_format: "F d Y H:i:s."

theme: default

plugins:
  - highlight

locale: "en"
locales: [en]

pages:
  main: home

errors:
  display: true

social_link:
  twitter: "https://twitter.com/getflextype"
  github: "https://github.com/flextype"
  gitter: "https://gitter.im/flextype/flextype"
  vkontakte: "https://vk.com/flextype"
  telegram: "http://t.me/flextype"

cache:
  enabled: true
  prefix: Flextype
  driver: auto
  lifetime: 604800
