#
# Site configuration
#

title: "Rawilum"
description: "Modern Open Source Flat-File Content Management System"
author:
  email: ""

timezone: UTC
charset: UTF-8

theme: default

plugins:

locale: "en"
locales: [en]

pages:
  flush_cache: false
  main: home

errors:
  display: false

cache:
  enabled: false
  prefix: Rawilum
  driver: auto
  lifetime: 604800
