#
# Site configuration
#

title: "Flextype"
description: "Modern Open Source Flat-File Content Management System"
author:
  email: ""

timezone: UTC
charset: UTF-8

theme: default

plugins:
  - highlight

locale: "en"
locales: [en]

pages:
  flush_cache: false
  main: home

errors:
  display: true

social_link:
  facebook: "https://www.facebook.com/flexgine"
  twitter: "https://twitter.com/flexgine"
  github: "https://github.com/flexgine"
  gitter: "https://gitter.im/flexgine/flexgine"
  vkontakte: "https://vk.com/flexgine"
  telegram: "http://t.me/flexgine"

cache:
  enabled: false
  prefix: Flextype
  driver: auto
  lifetime: 604800
