title: "Flextype"
description: "Modern Open Source Flat-File Content Management System"
keywords: "flextype, php, cms, flat-file cms, flat cms, flatfile cms, markdown"
robots: "index, follow"
author:
  name: "Sergey Romanenko"
  email: ""

social_link:
  twitter: "https://twitter.com/getflextype"
  github: "https://github.com/flextype"
  vkontakte: "https://vk.com/flextype"
  discord: "https://discord.gg/CCKPKVG"
  blog: "http://flextype.org/blog"
